<div class="loadingio-spinner-eclipse-6eyltf1usco" wire:loading>
	<div class="ldio-f50r66hren">
	</div>
	
	</div>
	</div>
</div>
@push('style')
<style type="text/css">
@keyframes ldio-f50r66hren {
  0% { transform: rotate(0deg) }
  50% { transform: rotate(180deg) }
  100% { transform: rotate(360deg) }
}
.ldio-f50r66hren div {
  position: absolute;
  animation: ldio-f50r66hren 1.8800000000000001s linear infinite;
  width: 82px;
  height: 82px;
  top: 9px;
  left: 9px;
  border-radius: 50%;
  box-shadow: 0 5.300000000000001px 0 0 #ffffff;
  transform-origin: 41px 43.65px;
}
.loadingio-spinner-eclipse-6eyltf1usco {
  width: 31px;
  height: 20px;
  display: inline-block;
  overflow: hidden;
  background: rgba(NaN, NaN, NaN, 0);
}
.ldio-f50r66hren {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.31);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-f50r66hren div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>

@endpush